default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  advisory_locks: false

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
